Run feature tests in parallel

diff --git a/script/feature-test b/script/feature-test
--- a/script/feature-test
+++ b/script/feature-test
@@ -1,17 +1,61 @@
 #!/usr/bin/env bash
 set -euxo pipefail
 IFS=$'\n\t'
-PATH=$(npm bin):$PATH
+export PATH=$(npm bin):$PATH
 
 export NODE_ENV=production
 export PORT=8010
+export INTERACTIVE_TIMEOUT="80000"
 
-./script/test-setup
+ISS_URL="http://localhost:5000/" ./script/test-setup
 
-# Point the app at our mock ISS instance.
-ISS_URL="http://localhost:5000/" ./script/recreate-dev-env-file
+function runTest {
+    JOB_NUM=$1
+    let "JOB_SLOT = $JOB_NUM % $CONCURRENCY"
+    let PORT=8010+$1*2
+    let ISS_MOCK_PORT=8011+$1*2
+    export ISS_URL="http://localhost:$ISS_MOCK_PORT"
+    export ENVFILE_PATH="/static/env-test-$1.js"
 
-# Saucelabs bails after 90 seconds inactivity, but otherwise we want
-# this quite high as it makes debugging the tests easier.
-INTERACTIVE_TIMEOUT="80000"
-mocha --compilers js:babel/register --timeout "$INTERACTIVE_TIMEOUT" test/yadda.js $@
+    ./script/generate-env-vars > "public/$ENVFILE_PATH"
+
+    export PORT
+    export ISS_MOCK_PORT
+
+    mocha \
+        --compilers js:babel/register \
+        --colors \
+        --timeout "$INTERACTIVE_TIMEOUT" \
+        --grep "$2" \
+        test/yadda.js \
+
+    sleep 1 # Avoid completely slamming the machine
+
+}
+
+export -f runTest
+
+CONCURRENCY=10
+
+if which sysctl > /dev/null ; then
+    NCPU="$(sysctl -n hw.ncpu || echo 10)"
+    let CONCURRENCY=2*$NCPU
+fi
+
+# google maps api is authed from :8010 to :8030
+# and we use 2 ports per process, so CONCURRENCY
+# higher than 10 will cause failed tests.
+if [ "$CONCURRENCY" -gt "10" ] ; then
+    CONCURRENCY=10
+fi
+
+export SHELL=/bin/bash
+export CONCURRENCY
+
+mocha \
+    --compilers js:babel/register \
+        test/yadda-list.js \
+        | grep '^[^[:space:]]' \
+        | parallel \
+            -j "$CONCURRENCY" \
+            runTest "{#}" "{1}"
